Document: tornado-relay
Title: Debian tornado-relay Manual
Author: <insert document author here>
Abstract: This manual describes what tornado-relay is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tornado-relay/tornado-relay.sgml.gz

Format: postscript
Files: /usr/share/doc/tornado-relay/tornado-relay.ps.gz

Format: text
Files: /usr/share/doc/tornado-relay/tornado-relay.text.gz

Format: HTML
Index: /usr/share/doc/tornado-relay/html/index.html
Files: /usr/share/doc/tornado-relay/html/*.html
